export const sections = [
  {
    bgColor: "bg-[#dfd6cf]",
    id: "01",
    offset: "0rem",
    imgSrc: "img/1.png",
    title: "XDog",
    subtitle:
      "Serveur Multi Mission Coverage Management pour Pléiades / Astroterra Et les futurs satellites d’observation de la terre.",
    text: "Conceptualiser et intégrer une interface pour Airbus afin de récupérer des données d'images satellites dans une zone définie par l'utilisateur.",
    highlightWord: ["Airbus"],
  },
  {
    bgColor: "bg-[#c5c3c0]",
    id: "02",
    offset: "2rem",
    imgSrc: "img/2.png",
    title: "Walk",
    subtitle: "gestion de maintenance moteur Safran",
    text: "Conceptualiser et intégrer un outil de maintenance de moteurs d'avions à destination des techniciens Safran.",
    highlightWord: ["Safran"],
  },
  {
    bgColor: "bg-[#dfd6cf]",
    id: "03",
    offset: "4rem",
    imgSrc: "img/3.png",
    title: "MyCM",
    subtitle: "Gestion humaine",
    text: "Une grande entreprise a besoin d'outil afin de gérer au mieux les relations humaines entre collaborateurs. je me suis occupé de l'intégration de la logique métier à destination des services RH Capgemini.",
    highlightWord: ["Capgemini"],
  },
  {
    bgColor: "bg-[#c5c3c0]",
    id: "04",
    offset: "6rem",
    imgSrc: "img/4.png",
    title: "Skywise",
    subtitle: "gestion de flote aéronautique",
    text: "Intégration de nouvelles interfaces, pour Airbus, à partir de maquettes UI/UX, à destination des compagnie aériennes afin de gérer au mieux la maintenance de leurs avions.",
    highlightWord: ["Airbus"],
  },
  {
    bgColor: "bg-[#dfd6cf]",
    id: "05",
    offset: "8rem",
    imgSrc: "img/5.png",
    title: "Mars2020",
    subtitle: "interface utilisateur pour mission Perseverance sur Mars",
    text: "Implémentation de nouvelles interfaces à destination des scientifiques du CNES et de la NASA afin d'envoyer des ordres de missions au robot Perseverance, présent sur Mars.",
    highlightWord: ["CNES", "NASA"],
  },
];
